name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Ensure you use the correct Python version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Debug Secrets
      run: |
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}"
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}"
        echo "Secrets are set"

    - name: Check environment variables
      run: |
        echo "DISCORD_TOKEN: $DISCORD_TOKEN"
        echo "OPENAI_API_KEY: $OPENAI_API_KEY"
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Run bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        source venv/bin/activate
        python code.py